export interface Review {
  id: string;
  reviewerName: string;
  rating: number;
  comment: string;
  image?: string;
  additionalImages?: string[];
}

export const reviewsData: Record<string, Review[]> = {
  "1": [
    {
      id: "1",
      reviewerName: "Anna",
      rating: 4,
      comment: "Pulen dan tidak mekar",
      image: "../images/beras-merah.jpg",
    },
    {
      id: "2",
      reviewerName: "Budi",
      rating: 5,
      comment: "Berasnya enak",
      image: "../images/beras-merah.jpg",
    },
  ],
  "2": [
    {
      id: "1",
      reviewerName: "Joan",
      rating: 4,
      comment: "Gurih dan nagih",
      image: "../images/kacang-mede.jpg",
    },
    {
      id: "2",
      reviewerName: "Syahrul",
      rating: 5,
      comment: "Kacang Medenya enak",
      image: "../images/kacang-mede.jpg",
    },
  ],
  "3": [
    {
      id: "1",
      reviewerName: "Lina",
      rating: 3,
      comment: "Rasanya lumayan",
      image: "../images/kol.jpg",
    },
    {
      id: "2",
      reviewerName: "Agus",
      rating: 4,
      comment: "Mienya enak",
      image: "../images/kol.jpg",
    },
  ],
  "4": [
    {
      id: "1",
      reviewerName: "Rahma",
      rating: 5,
      comment: "Super mantap!",
      image: "../images/terong.jpg",
    },
    {
      id: "2",
      reviewerName: "Ivan",
      rating: 4,
      comment: "enak dan pas",
      image: "../images/terong.jpg",
    },
  ],
  "5": [
    {
      id: "1",
      reviewerName: "Diana",
      rating: 5,
      comment: "Fresh dan bagus kualitasnya",
      image: "../images/tomat.jpg",
    },
    {
      id: "2",
      reviewerName: "Satria",
      rating: 4,
      comment: "Bagus untuk masakan",
      image: "../images/tomat.jpg",
    },
  ],
  "6": [
    {
      id: "1",
      reviewerName: "Rina",
      rating: 3,
      comment: "Lumayan, tapi kurang segar",
      image: "../images/tomat-ceri.jpg",
    },
    {
      id: "2",
      reviewerName: "Fajar",
      rating: 4,
      comment: "Tomatnya enak dan segar",
      image: "../images/tomat-ceri.jpg",
    },
  ],
  "7": [
    {
      id: "1",
      reviewerName: "Bima",
      rating: 5,
      comment: "Cabenya pedas",
      image: "../images/cabe-merah-keriting.jpg",
    },
    {
      id: "2",
      reviewerName: "Sinta",
      rating: 4,
      comment: "Fresh dan bagus",
      image: "../images/cabe-merah-keriting.jpg",
    },
  ],
  "8": [
    {
      id: "1",
      reviewerName: "Bima",
      rating: 5,
      comment: "Cabenya pedas",
      image: "../images/cabe-rawit.jpg",
    },
    {
      id: "2",
      reviewerName: "Sinta",
      rating: 4,
      comment: "Fresh dan bagus",
      image: "../images/cabe-rawit.jpg",
    },
  ],
  "9": [
    {
      id: "1",
      reviewerName: "Yuli",
      rating: 5,
      comment: "Teksturnya halus dan segar",
      image: "../images/paprika.jpg",
    },
    {
      id: "2",
      reviewerName: "Adi",
      rating: 4,
      comment: "Paprikanya enak dan pas",
      image: "../images/paprika.jpg",
    },
  ],
  "10": [
    {
      id: "1",
      reviewerName: "Tia",
      rating: 3,
      comment: "Sausnya terlalu manis",
      image: "../images/lada-hitam.jpg",
    },
    {
      id: "2",
      reviewerName: "Joko",
      rating: 4,
      comment: "Pas untuk berbagai masakan",
      image: "../images/lada-hitam.jpg",
    },
  ],
  "11": [
    {
      id: "1",
      reviewerName: "Ilham",
      rating: 5,
      comment: "Seledrinya enak",
      image: "../images/seledri.jpg",
    },
    {
      id: "2",
      reviewerName: "Rosa",
      rating: 4,
      comment: "Seledrinya mantap",
      image: "../images/seledri.jpg",
    },
  ],
  "12": [
    {
      id: "1",
      reviewerName: "Reza",
      rating: 3,
      comment: "Wortelnya agak kecil",
      image: "../images/wortel.jpg",
    },
    {
      id: "2",
      reviewerName: "Wina",
      rating: 4,
      comment: "Wortelnya segar dan enak",
      image: "../images/wortel.jpg",
    },
  ],
  "13": [
    {
      id: "1",
      reviewerName: "Alvin",
      rating: 5,
      comment: "Jahe favorit keluarga",
      image: "../images/jahe.jpg",
    },
    {
      id: "2",
      reviewerName: "Lia",
      rating: 4,
      comment: "Rasa jahenya mantap",
      image: "../images/jahe.jpg",
    },
  ],
  "14": [
    {
      id: "1",
      reviewerName: "Sari",
      rating: 5,
      comment: "Bawangnya asli, manisnya pas",
      image: "../images/bawang-bombai.jpg",
    },
    {
      id: "2",
      reviewerName: "Bayu",
      rating: 4,
      comment: "Manis dan sehat",
      image: "../images/bawang-bombai.jpg",
    },
  ],
  "15": [
    {
      id: "1",
      reviewerName: "Hana",
      rating: 3,
      comment: "Sedikit busuk",
      image: "../images/bawang-putih.jpg",
    },
    {
      id: "2",
      reviewerName: "Rian",
      rating: 4,
      comment: "Aromanya enak dan lembut",
      image: "../images/bawang-putih.jpg",
    },
  ],
  "16": [
    {
      id: "1",
      reviewerName: "Doni",
      rating: 5,
      comment: "Bawang favorit di rumah",
      image: "../images/bawang-merah.jpg",
    },
    {
      id: "2",
      reviewerName: "Vina",
      rating: 4,
      comment: "Rasanya gurih",
      image: "../images/bawang-merah.jpg",
    },
  ],
  "17": [
    {
      id: "1",
      reviewerName: "Eka",
      rating: 5,
      comment: "Almond dengan rasa yang enak",
      image: "../images/almond.jpg",
    },
    {
      id: "2",
      reviewerName: "Jefri",
      rating: 4,
      comment: "Enak untuk cemilan",
      image: "../images/almond.jpg",
    },
  ],
  "18": [
    {
      id: "1",
      reviewerName: "Citra",
      rating: 4,
      comment: "Bayamnya segar",
      image: "../images/bayam.jpg",
    },
    {
      id: "2",
      reviewerName: "Dede",
      rating: 5,
      comment: "Pas untuk sandwich",
      image: "../images/bayam.jpg",
    },
  ],
  "19": [
    {
      id: "1",
      reviewerName: "Linda",
      rating: 5,
      comment: "Sari buah segar dan nikmat",
      image: "../images/timun.jpg",
    },
    {
      id: "2",
      reviewerName: "Andi",
      rating: 4,
      comment: "Segar untuk diminum setiap hari",
      image: "../images/timun.jpg",
    },
  ],
  "20": [
    {
      id: "1",
      reviewerName: "Fauzi",
      rating: 3,
      comment: "Rasanya biasa saja",
      image: "../images/jagung.jpg",
    },
    {
      id: "2",
      reviewerName: "Maya",
      rating: 4,
      comment: "Baik untuk masakan sehari-hari",
      image: "../images/jagung.jpg",
    },
  ],
  "21": [
    {
      id: "1",
      reviewerName: "Leo",
      rating: 5,
      comment: "Kentang favorit",
      image: "../images/kentang.jpg",
    },
    {
      id: "2",
      reviewerName: "Tami",
      rating: 4,
      comment: "Fresh dan cepat pengirimannya",
      image: "../images/kentang.jpg",
    },
  ],
  "22": [
    {
      id: "1",
      reviewerName: "Oki",
      rating: 5,
      comment: "Brokoli dengan aroma khas",
      image: "../images/brokoli.jpg",
    },
    {
      id: "2",
      reviewerName: "Susi",
      rating: 4,
      comment: "Menyegarkan dan sehat",
      image: "../images/brokoli.jpg",
    },
  ],
  "23": [
    {
      id: "1",
      reviewerName: "Rudy",
      rating: 3,
      comment: "Kolnya agak tidak segar",
      image: "../images/kol-merah.jpg",
    },
    {
      id: "2",
      reviewerName: "Rita",
      rating: 4,
      comment: "Pas untuk barbeque",
      image: "../images/kol-merah.jpg",
    },
  ],
  "24": [
    {
      id: "1",
      reviewerName: "Zara",
      rating: 5,
      comment: "Fresh dan enak",
      image: "../images/daun-bawang.jpg",
    },
    {
      id: "2",
      reviewerName: "Ilham",
      rating: 4,
      comment: "Cocok untuk makanan",
      image: "../images/daun-bawang.jpg",
    },
  ],
  "25": [
    {
      id: "1",
      reviewerName: "Rina",
      rating: 5,
      comment: "Labu yang lembut dan gurih",
      image: "../images/labu.jpg",
    },
    {
      id: "2",
      reviewerName: "Bambang",
      rating: 4,
      comment: "Pas untuk sandwich",
      image: "../images/labu.jpg",
    },
  ],
  "26": [
    {
      id: "1",
      reviewerName: "Dewi",
      rating: 5,
      comment: "Apel favorit keluarga",
      image: "../images/apel-malang.jpg",
    },
    {
      id: "2",
      reviewerName: "Anwar",
      rating: 4,
      comment: "Rasanya manis",
      image: "../images/apel-malang.jpg",
    },
  ],
  "27": [
    {
      id: "1",
      reviewerName: "Fikri",
      rating: 5,
      comment: "Anggurnya bagus dan fresh",
      image: "../images/anggur.jpg",
    },
    {
      id: "2",
      reviewerName: "Wulan",
      rating: 4,
      comment: "Pas untuk sarapan",
      image: "../images/anggur.jpg",
    },
  ],
  "28": [
    {
      id: "1",
      reviewerName: "Nana",
      rating: 4,
      comment: "Nanasnya enak dan gurih",
      image: "../images/nanas-nemalang.jpg",
    },
    {
      id: "2",
      reviewerName: "Faisal",
      rating: 5,
      comment: "Sangat cocok untuk cemilan",
      image: "../images/nanas-nemalang.jpg",
    },
  ],
  "29": [
    {
      id: "1",
      reviewerName: "Cici",
      rating: 5,
      comment: "Pepaya yang enak",
      image: "../images/pepaya-california.jpg",
    },
    {
      id: "2",
      reviewerName: "Edo",
      rating: 4,
      comment: "Praktis untuk cemilan sehari-hari",
      image: "../images/pepaya-california.jpg",
    },
  ],
  "30": [
    {
      id: "1",
      reviewerName: "Novi",
      rating: 5,
      comment: "Enak dicampur untuk smoothies",
      image: "../images/pisang-sunpride.jpg",
    },
    {
      id: "2",
      reviewerName: "Roni",
      rating: 4,
      comment: "Pas untuk sarapan",
      image: "../images/pisang-sunpride.jpg",
    },
  ],
  "31": [
    {
      id: "1",
      reviewerName: "Tono",
      rating: 5,
      comment: "Belimbingnya segar dan enak",
      image: "../images/belimbing.jpg",
    },
    {
      id: "2",
      reviewerName: "Mila",
      rating: 4,
      comment: "Cocok untuk rujak",
      image: "../images/belimbing.jpg",
    },
  ],
  "32": [
    {
      id: "1",
      reviewerName: "Gilang",
      rating: 5,
      comment: "Enak untuk bikin smoothies",
      image: "../images/blueberry.jpg",
    },
    {
      id: "2",
      reviewerName: "Yuni",
      rating: 4,
      comment: "Fresh",
      image: "../images/blueberry.jpg",
    },
  ],
  "33": [
    {
      id: "1",
      reviewerName: "Rio",
      rating: 5,
      comment: "Buah dengan rasa mantap",
      image: "../images/buah-naga.jpg",
    },
    {
      id: "2",
      reviewerName: "Lani",
      rating: 4,
      comment: "Tidak busuk dan cepat pengirimannya",
      image: "../images/buah-naga.jpg",
    },
  ],
  "34": [
    {
      id: "1",
      reviewerName: "Rika",
      rating: 5,
      comment: "Fresh dan enak",
      image: "../images/cherry.jpg",
    },
    {
      id: "2",
      reviewerName: "Fahmi",
      rating: 4,
      comment: "Enak untuk ngemil",
      image: "../images/cherry.jpg",
    },
  ],
  "35": [
    {
      id: "1",
      reviewerName: "Lukman",
      rating: 4,
      comment: "Enak banget manis",
      image: "../images/durian.jpg",
    },
    {
      id: "2",
      reviewerName: "Sinta",
      rating: 5,
      comment: "Mantap",
      image: "../images/durian.jpg",
    },
  ],
  "36": [
    {
      id: "1",
      reviewerName: "Dina",
      rating: 5,
      comment: "Besar dan segar",
      image: "../images/jambu.jpg",
    },
    {
      id: "2",
      reviewerName: "Bimo",
      rating: 4,
      comment: "Manis dan cocok buat rujak",
      image: "../images/jambu.jpg",
    },
  ],
  "37": [
    {
      id: "1",
      reviewerName: "Ferry",
      rating: 5,
      comment: "Asam dan segar",
      image: "../images/jeruk.jpg",
    },
    {
      id: "2",
      reviewerName: "Gina",
      rating: 4,
      comment: "Pas untuk membuat jus",
      image: "../images/jeruk.jpg",
    },
  ],
  "38": [
    {
      id: "1",
      reviewerName: "Putri",
      rating: 5,
      comment: "Rasanya mantap",
      image: "../images/alpukat-mentega.jpg",
    },
    {
      id: "2",
      reviewerName: "Hendra",
      rating: 4,
      comment: "Enak dan sehat",
      image: "../images/alpukat-mentega.jpg",
    },
  ],
  "39": [
    {
      id: "1",
      reviewerName: "Ayu",
      rating: 5,
      comment: "Airnya enak",
      image: "../images/kelapa.jpg",
    },
    {
      id: "2",
      reviewerName: "Benny",
      rating: 4,
      comment: "Daging buahnya tebal",
      image: "../images/kelapa.jpg",
    },
  ],
  "40": [
    {
      id: "1",
      reviewerName: "Yana",
      rating: 4,
      comment: "Lemonnya segar",
      image: "../images/lemon.jpg",
    },
    {
      id: "2",
      reviewerName: "Aldo",
      rating: 5,
      comment: "Cocok untuk campuran jus",
      image: "../images/lemon.jpg",
    },
  ],
  "41": [
    {
      id: "1",
      reviewerName: "Raisa",
      rating: 5,
      comment: "Mangga favorit saya",
      image: "../images/mangga.jpg",
    },
    {
      id: "2",
      reviewerName: "Agus",
      rating: 4,
      comment: "Cocok untuk sarapan",
      image: "../images/mangga.jpg",
    },
  ],
  "42": [
    {
      id: "1",
      reviewerName: "Joko",
      rating: 5,
      comment: "Manggis yang enak",
      image: "../images/manggis.jpg",
    },
    {
      id: "2",
      reviewerName: "Wati",
      rating: 4,
      comment: "Pas untuk cemilan",
      image: "../images/manggis.jpg",
    },
  ],
  "43": [
    {
      id: "1",
      reviewerName: "Nina",
      rating: 5,
      comment: "Melon yang menyegarkan",
      image: "../images/melon.jpg",
    },
    {
      id: "2",
      reviewerName: "Bagus",
      rating: 4,
      comment: "Pas untuk acara kumpul-kumpul",
      image: "../images/melon.jpg",
    },
  ],
  "44": [
    {
      id: "1",
      reviewerName: "Zaki",
      rating: 5,
      comment: "Nangka favorit keluarga",
      image: "../images/nangka.jpg",
    },
    {
      id: "2",
      reviewerName: "Ayu",
      rating: 4,
      comment: "Cocok untuk dibuat sayur",
      image: "../images/nangka.jpg",
    },
  ],
  "45": [
    {
      id: "1",
      reviewerName: "Rico",
      rating: 5,
      comment: "Sari buah yang segar dan enak",
      image: "../images/pir.jpg",
    },
    {
      id: "2",
      reviewerName: "Mira",
      rating: 4,
      comment: "Cocok untuk acara keluarga",
      image: "../images/pir.jpg",
    },
  ],
  "46": [
    {
      id: "1",
      reviewerName: "Dedi",
      rating: 5,
      comment: "Buah favorit saya",
      image: "../images/semangka.jpg",
    },
    {
      id: "2",
      reviewerName: "Sari",
      rating: 4,
      comment: "Rasanya mantap",
      image: "../images/semangka.jpg",
    },
  ],
  "47": [
    {
      id: "1",
      reviewerName: "Erik",
      rating: 5,
      comment: "Strawberry yang lembut dan enak",
      image: "../images/strawberry.jpg",
    },
    {
      id: "2",
      reviewerName: "Nia",
      rating: 4,
      comment: "Pas untuk sarapan sehat",
      image: "../images/strawberry.jpg",
    },
  ],
  "48": [
    {
      id: "1",
      reviewerName: "Dian",
      rating: 5,
      comment: "Lychee yang segar dan manis",
      image: "../images/lychee.jpg",
    },
    {
      id: "2",
      reviewerName: "Hadi",
      rating: 4,
      comment: "Cocok untuk cemilan sehat",
      image: "../images/lychee.jpg",
    },
  ],
  "49": [
    {
      id: "1",
      reviewerName: "Tina",
      rating: 5,
      comment: "Buah favorit",
      image: "../images/kiwi.jpg",
    },
    {
      id: "2",
      reviewerName: "Irwan",
      rating: 4,
      comment: "Menyegarkan setelah olahraga",
      image: "../images/kiwi.jpg",
    },
  ],
  "50": [
    {
      id: "1",
      reviewerName: "Adi",
      rating: 5,
      comment: "Minuman jambu air yang segar",
      image: "../images/jambu-air.jpg",
    },
    {
      id: "2",
      reviewerName: "Farah",
      rating: 4,
      comment: "Cocok untuk rujak",
      image: "../images/jambu-air.jpg",
    },
  ],
  "51": [
    {
      id: "1",
      reviewerName: "Dewi",
      rating: 5,
      comment: "Ayam dan jagungnya segar",
      image: "../images/ayam-jagung.jpg",
    },
    {
      id: "2",
      reviewerName: "Anwar",
      rating: 4,
      comment: "Jagungnya manis",
      image: "../images/ayam-jagung.jpg",
    },
  ],
  "52": [
    {
      id: "1",
      reviewerName: "Fikri",
      rating: 5,
      comment: "Ayam dan tomatnnya bagus dan fresh",
      image: "../images/ayam-tomat.jpg",
    },
    {
      id: "2",
      reviewerName: "Wulan",
      rating: 4,
      comment: "Pas untuk sarapan",
      image: "../images/ayam-tomat.jpg",
    },
  ],
  "53": [
    {
      id: "1",
      reviewerName: "Nana",
      rating: 4,
      comment: "Seladanya fresh dan baru dipetik",
      image: "../images/dada-ayam-selada.jpg",
    },
    {
      id: "2",
      reviewerName: "Faisal",
      rating: 5,
      comment: "Dada ayamnya besar dan fresh",
      image: "../images/dada-ayam-selada.jpg",
    },
  ],
  "54": [
    {
      id: "1",
      reviewerName: "Cici",
      rating: 5,
      comment: "Cocok untuk barbeque",
      image: "../images/daging-sapi-sayur.jpg",
    },
    {
      id: "2",
      reviewerName: "Edo",
      rating: 4,
      comment: "Sayurnya segar dan tidak rusak",
      image: "../images/daging-sapi-sayur.jpg",
    },
  ],
  "55": [
    {
      id: "1",
      reviewerName: "Novi",
      rating: 5,
      comment: "Enak untuk caampuran sayur sop",
      image: "../images/daun-bawang-wortel.jpg",
    },
    {
      id: "2",
      reviewerName: "Roni",
      rating: 4,
      comment: "Wortelnya besar dan enak",
      image: "../images/daun-bawang-wortel.jpg",
    },
  ],
  "56": [
    {
      id: "1",
      reviewerName: "Tono",
      rating: 5,
      comment: "Kacangnya segar dan enak",
      image: "../images/kacang-mix.jpg",
    },
    {
      id: "2",
      reviewerName: "Mila",
      rating: 4,
      comment: "Cocok untuk salad",
      image: "../images/kacang-mix.jpg",
    },
  ],
  "57": [
    {
      id: "1",
      reviewerName: "Gilang",
      rating: 5,
      comment: "Harganya murah",
      image: "../images/kentang-nugget.jpg",
    },
    {
      id: "2",
      reviewerName: "Yuni",
      rating: 4,
      comment: "worth it",
      image: "../images/kentang-nugget.jpg",
    },
  ],
  "58": [
    {
      id: "1",
      reviewerName: "Rio",
      rating: 5,
      comment: "Pengirimannya cepat sekali",
      image: "../images/labu-kol.jpg",
    },
    {
      id: "2",
      reviewerName: "Lani",
      rating: 4,
      comment: "Tidak busuk dan cepat pengirimannya",
      image: "../images/labu-kol.jpg",
    },
  ],
  "59": [
    {
      id: "1",
      reviewerName: "Rika",
      rating: 5,
      comment: "Fresh dan enak",
      image: "../images/labu-ubi.jpg",
    },
    {
      id: "2",
      reviewerName: "Fahmi",
      rating: 4,
      comment: "Enak untuk ngemil",
      image: "../images/labu-ubi.jpg",
    },
  ],
  "60": [
    {
      id: "1",
      reviewerName: "Lukman",
      rating: 4,
      comment: "Enak banget manis",
      image: "../images/nanas-semangka.jpg",
    },
    {
      id: "2",
      reviewerName: "Sinta",
      rating: 5,
      comment: "Mantap",
      image: "../images/nanas-semangka.jpg",
    },
  ],
  "61": [
    {
      id: "1",
      reviewerName: "Dina",
      rating: 5,
      comment: "Besar dan segar",
      image: "../images/paket-kebab.jpg",
    },
    {
      id: "2",
      reviewerName: "Bimo",
      rating: 4,
      comment: "Manis dan cocok buat cemilan",
      image: "../images/paket-kebab.jpg",
    },
  ],
  "62": [
    {
      id: "1",
      reviewerName: "Ferry",
      rating: 5,
      comment: "Asam dan segar",
      image: "../images/paket-salad-1.jpg",
    },
    {
      id: "2",
      reviewerName: "Gina",
      rating: 4,
      comment: "Saladnya enak",
      image: "../images/paket-salad-1.jpg",
    },
  ],
  "63": [
    {
      id: "1",
      reviewerName: "Putri",
      rating: 5,
      comment: "Rasanya mantap",
      image: "../images/paket-salad-2.jpg",
    },
    {
      id: "2",
      reviewerName: "Hendra",
      rating: 4,
      comment: "Enak dan sehat",
      image: "../images/paket-salad-2.jpg",
    },
  ],
  "64": [
    {
      id: "1",
      reviewerName: "Ayu",
      rating: 5,
      comment: "Sayurnya enak",
      image: "../images/paket-sayur-sop.jpg",
    },
    {
      id: "2",
      reviewerName: "Benny",
      rating: 4,
      comment: "Pengirimannya cepat",
      image: "../images/paket-sayur-sop.jpg",
    },
  ],
  "65": [
    {
      id: "1",
      reviewerName: "Yana",
      rating: 4,
      comment: "Pisang dan mangganya segar",
      image: "../images/pisang-mangga.jpg",
    },
    {
      id: "2",
      reviewerName: "Aldo",
      rating: 5,
      comment: "Cocok untuk campuran jus",
      image: "../images/pisang-mangga.jpg",
    },
  ],
  "66": [
    {
      id: "1",
      reviewerName: "Raisa",
      rating: 5,
      comment: "Sayur dan buah favorit saya",
      image: "../images/sayur-buah.jpg",
    },
    {
      id: "2",
      reviewerName: "Agus",
      rating: 4,
      comment: "Cocok untuk sarapan",
      image: "../images/sayur-buah.jpg",
    },
  ],
  "67": [
    {
      id: "1",
      reviewerName: "Joko",
      rating: 5,
      comment: "Timun dan paprikanya yang enak",
      image: "../images/timun-paprika.jpg",
    },
    {
      id: "2",
      reviewerName: "Wati",
      rating: 4,
      comment: "Fresh",
      image: "../images/timun-paprika.jpg",
    },
  ],
  "68": [
    {
      id: "1",
      reviewerName: "Nina",
      rating: 5,
      comment: "Timun dan strawberry yang menyegarkan",
      image: "../images/timun-strawberry.jpg",
    },
    {
      id: "2",
      reviewerName: "Bagus",
      rating: 4,
      comment: "Pas untuk acara kumpul-kumpul",
      image: "../images/timun-strawberry.jpg",
    },
  ],
  "69": [
    {
      id: "1",
      reviewerName: "Zaki",
      rating: 5,
      comment: "Tomat favorit keluarga",
      image: "../images/tomat-bawang.jpg",
    },
    {
      id: "2",
      reviewerName: "Ayu",
      rating: 4,
      comment: "Cocok untuk dibuat sayur",
      image: "../images/tomat-bawang.jpg",
    },
  ],
  "70": [
    {
      id: "1",
      reviewerName: "Rico",
      rating: 5,
      comment: "Tomatnya segar dan enak",
      image: "../images/tomat-cabe.jpg",
    },
    {
      id: "2",
      reviewerName: "Mira",
      rating: 4,
      comment: "Cocok untuk dibuat sayur",
      image: "../images/tomat-cabe.jpg",
    },
  ],
  "71": [
    {
      id: "1",
      reviewerName: "Dedi",
      rating: 5,
      comment: "Dagingnya fresh dan bagus",
      image: "../images/daging-sapi-kentang.jpg",
    },
    {
      id: "2",
      reviewerName: "Sari",
      rating: 4,
      comment: "Rasanya mantap",
      image: "../images/daging-sapi-kentang.jpg",
    },
  ],
  "72": [
    {
      id: "1",
      reviewerName: "Erik",
      rating: 5,
      comment: "Tomat dan bawangnya enak",
      image: "../images/tomat-daun-bawang.jpg",
    },
    {
      id: "2",
      reviewerName: "Nia",
      rating: 4,
      comment: "Pas untuk sarapan sehat",
      image: "../images/tomat-daun-bawang.jpg",
    },
  ],
  "73": [
    {
      id: "1",
      reviewerName: "Dian",
      rating: 5,
      comment: "Tomat yang segar dan manis",
      image: "../images/tomat-hijau.jpg",
    },
    {
      id: "2",
      reviewerName: "Hadi",
      rating: 4,
      comment: "Cocok untuk cemilan sehat",
      image: "../images/tomat-hijau.jpg",
    },
  ],
  "74": [
    {
      id: "1",
      reviewerName: "Tina",
      rating: 5,
      comment: "Sayur favorit",
      image: "../images/ubi-sawi.jpg",
    },
    {
      id: "2",
      reviewerName: "Irwan",
      rating: 4,
      comment: "Enak untuk sarapan",
      image: "../images/ubi-sawi.jpg",
    },
  ],
  "75": [
    {
      id: "1",
      reviewerName: "Adi",
      rating: 5,
      comment: "pengirimannya cepat",
      image: "../images/wortel-jagung.jpg",
    },
    {
      id: "2",
      reviewerName: "Farah",
      rating: 4,
      comment: "Cocok untuk rujak",
      image: "../images/wortel-jagung.jpg",
    },
  ],
};
