export interface Review {
  id: string;
  reviewerName: string;
  rating: number;
  comment: string;
  image?: string;
  additionalImages?: string[];
}

export const reviewsData: Record<string, Review[]> = {
  "1": [
    {
      id: "1",
      reviewerName: "Anna",
      rating: 4,
      comment: "Pulen dan tidak mekar",
      image: "../images/Beras Merah.jpg",
    },
    {
      id: "2",
      reviewerName: "Budi",
      rating: 5,
      comment: "Berasnya enak",
      image: "../images/Beras Merah.jpg",
    },
  ],
  "2": [
    {
      id: "1",
      reviewerName: "Joan",
      rating: 4,
      comment: "Gurih dan nagih",
      image: "../images/Kacang Mede.jpg",
    },
    {
      id: "2",
      reviewerName: "Syahrul",
      rating: 5,
      comment: "Kacang Medenya enak",
      image: "../images/Kacang Mede.jpg",
    },
  ],
  "3": [
    {
      id: "1",
      reviewerName: "Lina",
      rating: 3,
      comment: "Rasanya lumayan",
      image: "../images/Kol.jpg",
    },
    {
      id: "2",
      reviewerName: "Agus",
      rating: 4,
      comment: "Mienya enak",
      image: "../images/Kol.jpg",
    },
  ],
  "4": [
    {
      id: "1",
      reviewerName: "Rahma",
      rating: 5,
      comment: "Super mantap!",
      image: "../images/Terong.jpg",
    },
    {
      id: "2",
      reviewerName: "Ivan",
      rating: 4,
      comment: "enak dan pas",
      image: "../images/Terong.jpg",
    },
  ],
  "5": [
    {
      id: "1",
      reviewerName: "Diana",
      rating: 5,
      comment: "Fresh dan bagus kualitasnya",
      image: "../images/Tomat.jpg",
    },
    {
      id: "2",
      reviewerName: "Satria",
      rating: 4,
      comment: "Bagus untuk masakan",
      image: "../images/Tomat.jpg",
    },
  ],
  "6": [
    {
      id: "1",
      reviewerName: "Rina",
      rating: 3,
      comment: "Lumayan, tapi kurang segar",
      image: "../images/Tomat Ceri.jpg",
    },
    {
      id: "2",
      reviewerName: "Fajar",
      rating: 4,
      comment: "Tomatnya enak dan segar",
      image: "../images/Tomat Ceri.jpg",
    },
  ],
  "7": [
    {
      id: "1",
      reviewerName: "Bima",
      rating: 5,
      comment: "Cabenya pedas",
      image: "../images/Cabe Merah Keriting.jpg",
    },
    {
      id: "2",
      reviewerName: "Sinta",
      rating: 4,
      comment: "Fresh dan bagus",
      image: "../images/Cabe Merah Keriting.jpg",
    },
  ],
  "8": [
    {
      id: "1",
      reviewerName: "Bima",
      rating: 5,
      comment: "Cabenya pedas",
      image: "../images/Cabe Rawit.jpg",
    },
    {
      id: "2",
      reviewerName: "Sinta",
      rating: 4,
      comment: "Fresh dan bagus",
      image: "../images/Cabe Rawit.jpg",
    },
  ],
  "9": [
    {
      id: "1",
      reviewerName: "Yuli",
      rating: 5,
      comment: "Teksturnya halus dan segar",
      image: "../images/Paprika.jpg",
    },
    {
      id: "2",
      reviewerName: "Adi",
      rating: 4,
      comment: "Paprikanya enak dan pas",
      image: "../images/Paprika.jpg",
    },
  ],
  "10": [
    {
      id: "1",
      reviewerName: "Tia",
      rating: 3,
      comment: "Sausnya terlalu manis",
      image: "../images/Lada Hitam.jpg",
    },
    {
      id: "2",
      reviewerName: "Joko",
      rating: 4,
      comment: "Pas untuk berbagai masakan",
      image: "../images/Lada Hitam.jpg",
    },
  ],
  "11": [
    {
      id: "1",
      reviewerName: "Ilham",
      rating: 5,
      comment: "Seledrinya enak",
      image: "../images/Seledri.jpg",
    },
    {
      id: "2",
      reviewerName: "Rosa",
      rating: 4,
      comment: "Seledrinya mantap",
      image: "../images/Seledri.jpg",
    },
  ],
  "12": [
    {
      id: "1",
      reviewerName: "Reza",
      rating: 3,
      comment: "Wortelnya agak kecil",
      image: "../images/Wortel.jpg",
    },
    {
      id: "2",
      reviewerName: "Wina",
      rating: 4,
      comment: "Wortelnya segar dan enak",
      image: "../images/Wortel.jpg",
    },
  ],
  "13": [
    {
      id: "1",
      reviewerName: "Alvin",
      rating: 5,
      comment: "Jahe favorit keluarga",
      image: "../images/Jahe.jpg",
    },
    {
      id: "2",
      reviewerName: "Lia",
      rating: 4,
      comment: "Rasa jahenya mantap",
      image: "../images/Jahe.jpg",
    },
  ],
  "14": [
    {
      id: "1",
      reviewerName: "Sari",
      rating: 5,
      comment: "Bawangnya asli, manisnya pas",
      image: "../images/Bawang Bombai.jpg",
    },
    {
      id: "2",
      reviewerName: "Bayu",
      rating: 4,
      comment: "Manis dan sehat",
      image: "../images/Bawang Bombai.jpg",
    },
  ],
  "15": [
    {
      id: "1",
      reviewerName: "Hana",
      rating: 3,
      comment: "Sedikit busuk",
      image: "../images/Bawang Putih.jpg",
    },
    {
      id: "2",
      reviewerName: "Rian",
      rating: 4,
      comment: "Aromanya enak dan lembut",
      image: "../images/Bawang Putih.jpg",
    },
  ],
  "16": [
    {
      id: "1",
      reviewerName: "Doni",
      rating: 5,
      comment: "Bawang favorit di rumah",
      image: "../images/Bawang Merah.jpg",
    },
    {
      id: "2",
      reviewerName: "Vina",
      rating: 4,
      comment: "Rasanya gurih",
      image: "../images/Bawang Merah.jpg",
    },
  ],
  "17": [
    {
      id: "1",
      reviewerName: "Eka",
      rating: 5,
      comment: "Almond dengan rasa yang enak",
      image: "../images/Almond.jpg",
    },
    {
      id: "2",
      reviewerName: "Jefri",
      rating: 4,
      comment: "Enak untuk cemilan",
      image: "../images/Almond.jpg",
    },
  ],
  "18": [
    {
      id: "1",
      reviewerName: "Citra",
      rating: 4,
      comment: "Bayamnya segar",
      image: "../images/Bayam.jpg",
    },
    {
      id: "2",
      reviewerName: "Dede",
      rating: 5,
      comment: "Pas untuk sandwich",
      image: "../images/Bayam.jpg",
    },
  ],
  "19": [
    {
      id: "1",
      reviewerName: "Linda",
      rating: 5,
      comment: "Sari buah segar dan nikmat",
      image: "../images/Timun.jpg",
    },
    {
      id: "2",
      reviewerName: "Andi",
      rating: 4,
      comment: "Segar untuk diminum setiap hari",
      image: "../images/Timun.jpg",
    },
  ],
  "20": [
    {
      id: "1",
      reviewerName: "Fauzi",
      rating: 3,
      comment: "Rasanya biasa saja",
      image: "../images/Jagung.jpg",
    },
    {
      id: "2",
      reviewerName: "Maya",
      rating: 4,
      comment: "Baik untuk masakan sehari-hari",
      image: "../images/Jagung.jpg",
    },
  ],
  "21": [
    {
      id: "1",
      reviewerName: "Leo",
      rating: 5,
      comment: "Kentang favorit",
      image: "../images/Kentang.jpg",
    },
    {
      id: "2",
      reviewerName: "Tami",
      rating: 4,
      comment: "Fresh dan cepat pengirimannya",
      image: "../images/Kentang.jpg",
    },
  ],
  "22": [
    {
      id: "1",
      reviewerName: "Oki",
      rating: 5,
      comment: "Brokoli dengan aroma khas",
      image: "../images/Brokoli.jpg",
    },
    {
      id: "2",
      reviewerName: "Susi",
      rating: 4,
      comment: "Menyegarkan dan sehat",
      image: "../images/Brokoli.jpg",
    },
  ],
  "23": [
    {
      id: "1",
      reviewerName: "Rudy",
      rating: 3,
      comment: "Kolnya agak tidak segar",
      image: "../images/Kol Merah.jpg",
    },
    {
      id: "2",
      reviewerName: "Rita",
      rating: 4,
      comment: "Pas untuk barbeque",
      image: "../images/Kol Merah.jpg",
    },
  ],
  "24": [
    {
      id: "1",
      reviewerName: "Zara",
      rating: 5,
      comment: "Fresh dan enak",
      image: "../images/Daun Bawang.jpg",
    },
    {
      id: "2",
      reviewerName: "Ilham",
      rating: 4,
      comment: "Cocok untuk makanan",
      image: "../images/Daun Bawang.jpg",
    },
  ],
  "25": [
    {
      id: "1",
      reviewerName: "Rina",
      rating: 5,
      comment: "Labu yang lembut dan gurih",
      image: "../images/Labu.jpg",
    },
    {
      id: "2",
      reviewerName: "Bambang",
      rating: 4,
      comment: "Pas untuk sandwich",
      image: "../images/Labu.jpg",
    },
  ],
  "26": [
    {
      id: "1",
      reviewerName: "Dewi",
      rating: 5,
      comment: "Apel favorit keluarga",
      image: "../images/Apel Malang.jpg",
    },
    {
      id: "2",
      reviewerName: "Anwar",
      rating: 4,
      comment: "Rasanya manis",
      image: "../images/Apel Malang.jpg",
    },
  ],
  "27": [
    {
      id: "1",
      reviewerName: "Fikri",
      rating: 5,
      comment: "Anggurnya bagus dan fresh",
      image: "../images/Anggur.jpg",
    },
    {
      id: "2",
      reviewerName: "Wulan",
      rating: 4,
      comment: "Pas untuk sarapan",
      image: "../images/Anggur.jpg",
    },
  ],
  "28": [
    {
      id: "1",
      reviewerName: "Nana",
      rating: 4,
      comment: "Nanasnya enak dan gurih",
      image: "../images/Nanas Pemalang.jpg",
    },
    {
      id: "2",
      reviewerName: "Faisal",
      rating: 5,
      comment: "Sangat cocok untuk cemilan",
      image: "../images/Nanas Pemalang.jpg",
    },
  ],
  "29": [
    {
      id: "1",
      reviewerName: "Cici",
      rating: 5,
      comment: "Pepaya yang enak",
      image: "../images/Pepaya California.jpg",
    },
    {
      id: "2",
      reviewerName: "Edo",
      rating: 4,
      comment: "Praktis untuk cemilan sehari-hari",
      image: "../images/Pepaya California.jpg",
    },
  ],
  "30": [
    {
      id: "1",
      reviewerName: "Novi",
      rating: 5,
      comment: "Enak dicampur untuk smoothies",
      image: "../images/Pisang Sunpride.jpg",
    },
    {
      id: "2",
      reviewerName: "Roni",
      rating: 4,
      comment: "Pas untuk sarapan",
      image: "../images/Pisang Sunpride.jpg",
    },
  ],
  "31": [
    {
      id: "1",
      reviewerName: "Tono",
      rating: 5,
      comment: "Belimbingnya segar dan enak",
      image: "../images/Belimbing.jpg",
    },
    {
      id: "2",
      reviewerName: "Mila",
      rating: 4,
      comment: "Cocok untuk rujak",
      image: "../images/Belimbing.jpg",
    },
  ],
  "32": [
    {
      id: "1",
      reviewerName: "Gilang",
      rating: 5,
      comment: "Enak untuk bikin smoothies",
      image: "../images/Blueberry.jpg",
    },
    {
      id: "2",
      reviewerName: "Yuni",
      rating: 4,
      comment: "Fresh",
      image: "../images/Blueberry.jpg",
    },
  ],
  "33": [
    {
      id: "1",
      reviewerName: "Rio",
      rating: 5,
      comment: "Buah dengan rasa mantap",
      image: "../images/Buah Naga.jpg",
    },
    {
      id: "2",
      reviewerName: "Lani",
      rating: 4,
      comment: "Tidak busuk dan cepat pengirimannya",
      image: "../images/Buah Naga.jpg",
    },
  ],
  "34": [
    {
      id: "1",
      reviewerName: "Rika",
      rating: 5,
      comment: "Fresh dan enak",
      image: "../images/Cherry.jpg",
    },
    {
      id: "2",
      reviewerName: "Fahmi",
      rating: 4,
      comment: "Enak untuk ngemil",
      image: "../images/Cherry.jpg",
    },
  ],
  "35": [
    {
      id: "1",
      reviewerName: "Lukman",
      rating: 4,
      comment: "Enak banget manis",
      image: "../images/Durian.jpg",
    },
    {
      id: "2",
      reviewerName: "Sinta",
      rating: 5,
      comment: "Mantap",
      image: "../images/Durian.jpg",
    },
  ],
  "36": [
    {
      id: "1",
      reviewerName: "Dina",
      rating: 5,
      comment: "Besar dan segar",
      image: "../images/Jambu.jpg",
    },
    {
      id: "2",
      reviewerName: "Bimo",
      rating: 4,
      comment: "Manis dan cocok buat rujak",
      image: "../images/Jambu.jpg",
    },
  ],
  "37": [
    {
      id: "1",
      reviewerName: "Ferry",
      rating: 5,
      comment: "Asam dan segar",
      image: "../images/Jeruk.jpg",
    },
    {
      id: "2",
      reviewerName: "Gina",
      rating: 4,
      comment: "Pas untuk membuat jus",
      image: "../images/Jeruk.jpg",
    },
  ],
  "38": [
    {
      id: "1",
      reviewerName: "Putri",
      rating: 5,
      comment: "Rasanya mantap",
      image: "../images/Alpukat Mentega.jpg",
    },
    {
      id: "2",
      reviewerName: "Hendra",
      rating: 4,
      comment: "Enak dan sehat",
      image: "../images/Alpukat Mentega.jpg",
    },
  ],
  "39": [
    {
      id: "1",
      reviewerName: "Ayu",
      rating: 5,
      comment: "Airnya enak",
      image: "../images/Kelapa.jpg",
    },
    {
      id: "2",
      reviewerName: "Benny",
      rating: 4,
      comment: "Daging buahnya tebal",
      image: "../images/Kelapa.jpg",
    },
  ],
  "40": [
    {
      id: "1",
      reviewerName: "Yana",
      rating: 4,
      comment: "Lemonnya segar",
      image: "../images/Lemon.jpg",
    },
    {
      id: "2",
      reviewerName: "Aldo",
      rating: 5,
      comment: "Cocok untuk campuran jus",
      image: "../images/Lemon.jpg",
    },
  ],
  "41": [
    {
      id: "1",
      reviewerName: "Raisa",
      rating: 5,
      comment: "Mangga favorit saya",
      image: "../images/Mangga.jpg",
    },
    {
      id: "2",
      reviewerName: "Agus",
      rating: 4,
      comment: "Cocok untuk sarapan",
      image: "../images/Mangga.jpg",
    },
  ],
  "42": [
    {
      id: "1",
      reviewerName: "Joko",
      rating: 5,
      comment: "Manggis yang enak",
      image: "../images/Manggis.jpg",
    },
    {
      id: "2",
      reviewerName: "Wati",
      rating: 4,
      comment: "Pas untuk cemilan",
      image: "../images/Manggis.jpg",
    },
  ],
  "43": [
    {
      id: "1",
      reviewerName: "Nina",
      rating: 5,
      comment: "Melon yang menyegarkan",
      image: "../images/Melon.jpg",
    },
    {
      id: "2",
      reviewerName: "Bagus",
      rating: 4,
      comment: "Pas untuk acara kumpul-kumpul",
      image: "../images/Melon.jpg",
    },
  ],
  "44": [
    {
      id: "1",
      reviewerName: "Zaki",
      rating: 5,
      comment: "Nangka favorit keluarga",
      image: "../images/Nangka.jpg",
    },
    {
      id: "2",
      reviewerName: "Ayu",
      rating: 4,
      comment: "Cocok untuk dibuat sayur",
      image: "../images/nangka.jpg",
    },
  ],
  "45": [
    {
      id: "1",
      reviewerName: "Rico",
      rating: 5,
      comment: "Sari buah yang segar dan enak",
      image: "../images/Pir.jpg",
    },
    {
      id: "2",
      reviewerName: "Mira",
      rating: 4,
      comment: "Cocok untuk acara keluarga",
      image: "../images/Pir.jpg",
    },
  ],
  "46": [
    {
      id: "1",
      reviewerName: "Dedi",
      rating: 5,
      comment: "Buah favorit saya",
      image: "../images/Semangka.jpg",
    },
    {
      id: "2",
      reviewerName: "Sari",
      rating: 4,
      comment: "Rasanya mantap",
      image: "../images/Semangka.jpg",
    },
  ],
  "47": [
    {
      id: "1",
      reviewerName: "Erik",
      rating: 5,
      comment: "Strawberry yang lembut dan enak",
      image: "../images/Strawberry.jpg",
    },
    {
      id: "2",
      reviewerName: "Nia",
      rating: 4,
      comment: "Pas untuk sarapan sehat",
      image: "../images/Strawberry.jpg",
    },
  ],
  "48": [
    {
      id: "1",
      reviewerName: "Dian",
      rating: 5,
      comment: "Lychee yang segar dan manis",
      image: "../images/Lychee.jpg",
    },
    {
      id: "2",
      reviewerName: "Hadi",
      rating: 4,
      comment: "Cocok untuk cemilan sehat",
      image: "../images/Lychee.jpg",
    },
  ],
  "49": [
    {
      id: "1",
      reviewerName: "Tina",
      rating: 5,
      comment: "Buah favorit",
      image: "../images/Kiwi.jpg",
    },
    {
      id: "2",
      reviewerName: "Irwan",
      rating: 4,
      comment: "Menyegarkan setelah olahraga",
      image: "../images/Kiwi.jpg",
    },
  ],
  "50": [
    {
      id: "1",
      reviewerName: "Adi",
      rating: 5,
      comment: "Minuman jambu air yang segar",
      image: "../images/Jambu Air.jpg",
    },
    {
      id: "2",
      reviewerName: "Farah",
      rating: 4,
      comment: "Cocok untuk rujak",
      image: "../images/Jambu Air.jpg",
    },
  ],
};
